[theme]
base="dark"
primaryColor="#00f3ff"
backgroundColor="#0e1117"
secondaryBackgroundColor="#262730"
textColor="#fafafa"
font="sans serif"

[client]
toolbarMode = "viewer"
showSidebarNavigation = false

[ui]
hideTopBar = true

[browser]
gatherUsageStats = false
